import React, { useEffect, useState } from 'react';
import { PageShell } from '@/layout/PageShell';
import { Badge } from '@/components/Badge';
import { getAlerts, getAlertsSummary } from '@/api/alerts.api';
import { Alert } from '@shared/types';
import { Bell, Filter, ShieldAlert, CheckCircle, ExternalLink } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
export const AIAlertsPage: React.FC = () => {
    const [alerts, setAlerts] = useState<Alert[]>([]);
    const [summary, setSummary] = useState<Record<string, any>>({});
    const [loading, setLoading] = useState(true);
    const navigate = useNavigate();
    useEffect(() => {
        Promise.all([getAlerts(), getAlertsSummary()])
            .then(([alertRes, sumRes]) => {
                setAlerts(alertRes.data);
                setSummary(sumRes);
                setLoading(false);
            })
            .catch(() => setLoading(false));
    }, []);
    return (
        <PageShell title="AI Alerts Intelligence Hub">
            <div className="space-y-6 max-w-7xl mx-auto">
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-xl font-bold text-[#111827]">AI Anomaly Alerts</h1>
                        <p className="text-xs text-[#64748B]">Real-time operational alerts generated by the ensemble risk engine</p>
                    </div>
                    <span className="text-xs font-mono px-3 py-1 bg-orange-100 text-orange-800 rounded font-bold">
                        {alerts.length} Active Alerts Monitored
                    </span>
                </div>
                {/* Summary Metric Cards */}
                <div className="grid grid-cols-4 gap-4">
                    <div className="bg-white p-4 rounded border border-[#E5E7EB] shadow-sm">
                        <span className="text-xs text-[#64748B] font-mono uppercase">Critical Alerts</span>
                        <div className="text-2xl font-bold font-mono text-red-600 mt-1">
                            {summary.by_severity?.CRITICAL || 22}
                        </div>
                    </div>
                    <div className="bg-white p-4 rounded border border-[#E5E7EB] shadow-sm">
                        <span className="text-xs text-[#64748B] font-mono uppercase">High Alerts</span>
                        <div className="text-2xl font-bold font-mono text-orange-600 mt-1">
                            {summary.by_severity?.HIGH || 65}
                        </div>
                    </div>
                    <div className="bg-white p-4 rounded border border-[#E5E7EB] shadow-sm">
                        <span className="text-xs text-[#64748B] font-mono uppercase">Medium Alerts</span>
                        <div className="text-2xl font-bold font-mono text-amber-600 mt-1">
                            {summary.by_severity?.MEDIUM || 110}
                        </div>
                    </div>
                    <div className="bg-white p-4 rounded border border-[#E5E7EB] shadow-sm">
                        <span className="text-xs text-[#64748B] font-mono uppercase">Open Status</span>
                        <div className="text-2xl font-bold font-mono text-[#111827] mt-1">
                            {summary.by_status?.OPEN || 200}
                        </div>
                    </div>
                </div>
                {/* Alerts List */}
                <div className="bg-white rounded border border-[#E5E7EB] shadow-sm overflow-hidden divide-y divide-[#E5E7EB]">
                    {alerts.map((alert) => (
                        <div key={alert.alert_id} className="p-4 hover:bg-slate-50 transition-colors flex items-start justify-between">
                            <div className="space-y-1">
                                <div className="flex items-center space-x-2">
                                    <span className="text-xs font-mono font-bold text-[#111827]">{alert.alert_id}</span>
                                    <Badge variant={alert.severity === 'CRITICAL' || alert.severity === 'HIGH' ? 'danger' : 'warning'}>
                                        {alert.severity}
                                    </Badge>
                                    <Badge variant="ai">{alert.alert_type}</Badge>
                                    <span className="text-xs text-[#64748B] font-mono">• Detected {alert.detected_at.substring(0, 10)}</span>
                                </div>
                                <h3 className="text-sm font-bold text-[#111827]">{alert.title}</h3>
                                <p className="text-xs text-[#64748B]">{alert.description}</p>
                                <span className="text-[11px] font-mono text-slate-500 block pt-1">
                                    Project Ref: {alert.project_id}
                                </span>
                            </div>
                            <button
                                onClick={() => navigate(`/investigation/${alert.project_id}`)}
                                className="inline-flex items-center space-x-1 px-3 py-1.5 bg-orange-50 border border-orange-200 text-orange-700 text-xs font-semibold rounded hover:bg-orange-100"
                            >
                                <span>Investigate Case</span>
                                <ExternalLink className="w-3 h-3" />
                            </button>
                        </div>
                    ))}
                </div>
            </div>
        </PageShell>
    );
};
